### ISSUE TITLE
Competitive advantages and possible effects if the project fails

### ISSUE THREAD

**Issue by AndrewDucDanhDo** [AndrewDucDanhDo/Information_System_Development_Methodologies#11]

**Comment by adamkondonis** [comment]
Competitive advantage and benefits to the call management centre have been outlined. We stated that implementing a new system can assist the travel company to gain competitive advantage over other competitors which can support the company to improve sales and interaction with customers. However, we need to discuss the possible effects if the project fails. It might be a good idea for the team to brainstorm ideas together as to what may happen if the project potentially fails.
