### ISSUE TITLE
Create User Stories and Use Case Diagrams

### ISSUE THREAD

**Issue by AndrewDucDanhDo** [AndrewDucDanhDo/Information_System_Development_Methodologies#7]
Should include Version 1.0 and Version 2.0 of Use Case Diagrams

**Comment by Louis427** [comment]
Use case diagram is currently being refined. Will need to check with tutor how many user stories are needed due to a misunderstanding/misreading of the workproducts, models and descriptions marking criteria.

**Comment by AndrewDucDanhDo** [comment]
Use case diagrams are completed and uploaded. Next step will be to provide description summaries of the use cases in the report.
