### ISSUE TITLE
Create Activity Diagrams

### ISSUE THREAD

**Issue by AndrewDucDanhDo** [AndrewDucDanhDo/Information_System_Development_Methodologies#8]
Should include Version 1.0 and Version 2.0 of Activity Diagrams

**Comment by Louis427** [comment]
First iteration of the activity diagram for inbound calls. This iteration was done to see how the general structure could be, and as a result, the diagram will need to be more condensed so it is a more appropriate size for the report. 
Further iterations will include necessary features and an overall refinement.

In case the image attached makes it difficult to zoom in and out efficiently, click the link below which is where the activity diagrams are being made.
https://app.diagrams.net/#G1prqU7754M597c50upb0UtkVTjRMcSTUh

![Activity Diagram](https://user-images.githubusercontent.com/51735553/82661763-f392ab80-9c6f-11ea-9c0c-122f7b2047b3.png)

**Comment by Louis427** [comment]
Just like the inbound call, this activity diagram for the outbound call is currently in its first iteration which is used to see the general structure. Further iterations will have necessary and an overall refinement. 

In case the image attached makes it difficult to zoom in and out efficiently, click the link below which is where the activity diagrams are being made.
https://app.diagrams.net/#G1prqU7754M597c50upb0UtkVTjRMcSTUh

![Activity Diagram (1)](https://user-images.githubusercontent.com/51735553/82666875-1c1fa300-9c7a-11ea-86a8-d2856e140281.png)

**Comment by AndrewDucDanhDo** [comment]
These look really good. Approved! Could you upload these images and add them to the report?

**Comment by Louis427** [comment]
Final activity diagrams for inbound and outbound calls. Some refinements have been made, however, the diagrams were unable to be made smaller due to how complex the system is.

![Activity Diagram (3)](https://user-images.githubusercontent.com/51735553/82807238-b7a75280-9eca-11ea-86f9-a4635beb7a12.png)

![Activity Diagram (4)](https://user-images.githubusercontent.com/51735553/82807252-bf66f700-9eca-11ea-9277-1a9d26618aef.png)

**Comment by AndrewDucDanhDo** [comment]
Activity diagrams have been uploaded
